services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud123
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost,127.0.0.1
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_themes:/var/www/html/themes
      - /home/home/Documents:/documents:rw  # Writable access to Documents for management
    ports:
      - "9000:80"
    networks:
      - nextcloud_network
    restart: unless-stopped
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud123
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud_network
    restart: unless-stopped

networks:
  nextcloud_network:
    driver: bridge

volumes:
  # Nextcloud volumes
  nextcloud_data:
    driver: local
  nextcloud_config:
    driver: local
  nextcloud_apps:
    driver: local
  nextcloud_themes:
    driver: local
  nextcloud_db:
    driver: local 
